### ISSUE TITLE
ikev1 psk main mode with MD5

### ISSUE THREAD

**Issue by aswywy** [RUB-NDS/ikev1-psk-main-mode-dict-attacker#1]
Hi:
     I know that hashcat provide both  MD5 and SHA-1 in IKE PSK aggressive  mode cracker.but HC do not provide any IKE PSK main mode cracker.I thought IKE PSK main mode cannot be cracked before I saw your code.
     But now I wonder is there a way to crack IKE PSK main mode with MD5?And what is the different between MD5 and SHA-1 in the crackers?Just Keep the process the same and replace the HMAC SHA-1 kernel to MD5 kernel?
     Thank you very much.
     In addition,I use your code for test with python2.7 ubuntu1604,and it gets error as follow:

Traceback (most recent call last):
  File "main.py", line 85, in <module>
    if(checkIDValue(psk, dhSecret, initCookie, respCookie, initNonce, respNonce, iv, ciphertext)):
  File "main.py", line 41, in checkIDValue
    if(str(binascii.hexlify(plaintext)[:idLength].lower(),"ascii") ==
TypeError: str() takes at most 1 argument (2 given)

**Comment by Kaedo** [comment]
As far as I understand the only difference between MD5 and SHA-1 happens in the key derivation, so a replacing sha1 with md5 should be sufficient for my script.

For Hashcat this is more complicated because, in the aggressive mode, which is supported by HC, there is no encryption of the hash value. Therefore, an implementation of Main mode cracking needs to be integrated into HC before you could use it.

It is a python 3 script, the answer: https://stackoverflow.com/a/42347187
